import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import type { Pool } from "pg";
import reviewed from "../scripts/customer-updates/miopages-focus-reviewed.json";
import { readBasis } from "../lib/platform/operator-qc/context";
import { fingerprint } from "../lib/platform/canonical/model";
import { assessment,assertFresh,attest,checks,createPacket,normalizeBrief,saveFinding,saveResolution,setCheck,type Basis,type Packet } from "../lib/platform/operator-qc/model";
import { report } from "../scripts/operator-qc/report";

const sectionId=reviewed.after.sections.find(s=>s.type==="hero")!.id as string;
const base=():Basis=>({version:1,reviewedAt:"2026-10-08T00:00:00Z",target:reviewed.target,canonicalFingerprint:"a".repeat(64),siteFingerprint:"b".repeat(64),acquisitionFingerprint:"c".repeat(64),contextFingerprint:"d".repeat(64),presentation:{grammar:"service-led",version:3},routes:[{id:reviewed.after.pages[0].id,slug:"/"}],sections:[{id:sectionId,page_id:reviewed.after.pages[0].id}],actions:[],truth:[],needs:[],acquisition:[],technical:{status:"collected",buildId:"build",renderContext:"e".repeat(64),routes:[{status:200}],views:[{view:"desktop",h1Count:1},{view:"tablet",h1Count:1},{view:"mobile",h1Count:1}],limitations:[]},limitations:[]});
function passed(){const b=base();for(const v of b.technical.views)v.pageId=b.routes[0].id;let p=createPacket(b);for(const c of checks.filter(c=>c!=="readiness"))p=setCheck(p,c,"pass","Synthetic operator evidence","fixture operator");return p;}
const finding={reference:{sectionId},check:"imagery",severity:"blocker",problem:"Misleading image",evidence:"Synthetic exact candidate observation",effects:["trust"],visitorProblem:"Visitor infers fake proof",expectedImprovement:"No fabricated evidence",responsible:"operator",nextAction:"Choose a bounded alternative",status:"open"};
test("QC packet starts entirely unassessed and never auto-attests readiness",()=>{const p=createPacket(base());assert.equal(p.basisDigest,fingerprint(p.basis));assert.ok(Object.values(p.checklist).every(c=>c.status==="not assessed"));assert.equal(assessment(p).customerReady,false);assert.throws(()=>attest(p,"ready","fixture operator","Test"));assert.equal(p.attestations.length,0);});
test("exact context, acquisition history, build and packet integrity detect staleness",()=>{const p=createPacket(base());assert.doesNotThrow(()=>assertFresh(p,base()));assert.throws(()=>assertFresh(p,{...base(),contextFingerprint:"f".repeat(64)}),/Stale/);p.basis.presentation={altered:true};assert.throws(()=>assertFresh(p,base()),/altered/);});
test("mandatory checks cannot become not-applicable or readiness bypasses",()=>{const p=createPacket(base());assert.throws(()=>setCheck(p,"proofreading","not applicable","Skip","fixture operator"));assert.throws(()=>setCheck(p,"readiness","pass","Skip","fixture operator"));assert.throws(()=>setCheck(p,"brand","unknown" as never,"Skip","fixture operator"));assert.equal(assessment(setCheck(p,"imagery","not applicable","No imagery applies","fixture operator")).customerReady,false);});
test("finding severity and closure/deferral are bounded and tenant-scoped",()=>{const p=passed();const f=saveFinding(p,finding,"fixture operator").findings[0];assert.throws(()=>saveFinding(p,{...f,status:"resolved"},"fixture operator"));assert.throws(()=>saveFinding(p,{...f,status:"deferred",deferral:"Later"},"fixture operator"));assert.throws(()=>saveFinding(p,{...finding,reference:{sectionId:"00000000-0000-4000-8000-000000000001"}},"fixture operator"),/Foreign/);const q=saveFinding(p,{...f,status:"resolved",closure:"Verified corrected presentation"},"fixture operator");assert.equal(q.findings[0].status,"resolved");assert.equal(p.findings.length,0);assert.throws(()=>saveFinding(p,{...finding,css:"red"},"fixture operator"),/Unknown/);});
test("blockers, required corrections and unassessed checks refuse readiness",()=>{for(const severity of ["blocker","required correction"]){const p=saveFinding(passed(),{...finding,severity},"fixture operator");assert.equal(assessment(p).eligibleForAttestation,false);assert.throws(()=>attest(p,"ready","fixture operator","Test"));}const p=setCheck(passed(),"content","not assessed","Not reviewed","fixture operator");assert.equal(assessment(p).eligibleForAttestation,false);});
test("explicit local operator attestation requires complete evidence and invalidates on edits",()=>{const p=passed();assert.equal(assessment(p).eligibleForAttestation,true);assert.equal(assessment(p).customerReady,false);const a=attest(p,"ready","fixture operator","Reviewed synthetic outcome");assert.equal(assessment(a).customerReady,true);assert.equal(a.checklist.readiness.status,"pass");assert.equal(assessment(a).customerAcceptance,false);assert.equal(assessment(a).publicationAuthorized,false);assert.equal(assessment(setCheck(a,"content","pass","Changed review evidence","fixture operator")).customerReady,false);assert.equal(assessment(attest(a,"not-ready","fixture operator","Reassess")).customerReady,false);});
test("technical evidence completeness never means aesthetic approval",()=>{const p=passed();p.basis.technical.views[0].overflow=true;assert.equal(assessment(p).eligibleForAttestation,false);const q=passed();q.basis.technical.views.pop();assert.equal(assessment(q).eligibleForAttestation,false);});
test("duplicated viewport evidence and corrupted local findings cannot satisfy review",()=>{const p=passed();p.basis.technical.views[1].view="desktop";assert.equal(assessment(p).eligibleForAttestation,false);const q=passed();q.findings=[{...finding,id:"00000000-0000-4000-8000-000000000001",severity:"blocker",status:"deferred",deferral:"Skip"} as never];assert.throws(()=>assertFresh(q,q.basis),/closure/);});
function needPacket():Packet {const b=base();b.needs=[{sectionId,pageId:String(b.routes[0].id),route:"/",role:"service-illustration",importance:"important",purpose:"Clarity",source:"customer-owned",permission:"unresolved",classification:"unassessed",copy:{heading:"Clarity"},fallback:"Omitted safely",history:[],assets:[],heroDecision:["atmosphere / brand reinforcement","deterministic reinforcement","no image"]}];return createPacket(b);}
test("proposed visual strategies never execute and critical fallback needs explicit reassessment",()=>{let p=needPacket();assert.ok(assessment(p).reasons.some(r=>r.includes("Visual need unassessed")));for(const choice of ["customer-owned","existing-site","stock","generated","deterministic","commissioned","omit","refine-brief"]){const q=saveResolution(p,{sectionId,choice,classification:"atmosphere-brand",criticality:"critical",disposition:"requires-resolution",reason:"Review context",disclosure:"Imagery pending"},"fixture operator");assert.equal(q.resolutions[0].choice,choice);assert.ok(assessment(q).reasons.some(r=>r.includes("Critical visual")));}p=saveResolution(p,{sectionId,choice:"omit",classification:"no-visual",criticality:"critical",disposition:"adequate-fallback",reason:"Copy and existing presentation adequate",disclosure:"Optional illustration omitted"},"fixture operator");assert.ok(!assessment(p).reasons.some(r=>r.includes("Critical visual")));});
test("structured brief is bounded, scoped and contains no raw design controls",()=>{const p=needPacket(),brief={context:{sectionId,fingerprint:p.basis.contextFingerprint},classification:"atmosphere-brand",semanticGoal:"Clarity",visualStory:"One coherent presence",keyElements:["form"],exclusions:["UI"],composition:"Negative space",orientation:"landscape",styleTone:"Flat",brandConstraints:["Purple"],truthBoundary:"illustrative",acceptanceCriteria:["Supports copy"],workPolicy:{maxAttempts:0,maxRetries:0,budgetMicros:0,stopCondition:"No work authorized"}};assert.ok(normalizeBrief(p,brief));assert.throws(()=>normalizeBrief(p,{...brief,keyElements:Array(6).fill("form")}));assert.throws(()=>normalizeBrief(p,{...brief,context:{...brief.context,fingerprint:"stale"}}));assert.throws(()=>normalizeBrief(p,{...brief,classification:"proof-evidence"}));assert.throws(()=>normalizeBrief(p,{...brief,css:"color:red"}));});
test("current canonical packet reads exclusively and presents all five needs without mutation",async()=>{
  const state=structuredClone(reviewed.after) as Record<string,Record<string,unknown>[]>,before=fingerprint(state),sql:string[]=[];
  const pool={connect:async()=>({query:async(query:string)=>{sql.push(query);if(query.includes("to_regclass"))return {rows:[{relation:null}]};if(query.startsWith("SELECT to_jsonb")){const table=query.match(/FROM ([a-z_.]+)/)![1];return {rows:(state[table]??[]).map(row=>({row}))};}if(!/^(BEGIN|SET|ROLLBACK)/.test(query))throw Error("Unexpected SQL");return {rows:[]};},release(){}})} as unknown as Pool;
  const b=await readBasis(pool,{target:reviewed.target,buildId:"one"});assert.equal(b.needs.length,5);assert.ok(b.needs.some(n=>n.heroDecision?.length===3));assert.ok(sql[0].includes("READ ONLY"));assert.ok(sql.every(s=>/^(SELECT|BEGIN|SET|ROLLBACK)/.test(s)));assert.equal(fingerprint(state),before);
  const changed=await readBasis(pool,{target:reviewed.target,buildId:"two"});assert.notEqual(b.contextFingerprint,changed.contextFingerprint);
  await assert.rejects(readBasis(pool,{target:{...reviewed.target,managedSiteId:"00000000-0000-4000-8000-000000000001"},buildId:"one"}),/Unknown/);
});
test("Hero report distinguishes persisted reviews from semantic learning and shows escalation",()=>{const p=needPacket();p.basis.needs[0].history=[1,2,3].map(iteration=>({id:`job-${iteration}`,iteration,status:iteration===3?"awaiting-review":"completed",attempts:1,retries:0,reservedMicros:500000,budgetMicros:iteration===3?1500000:1000000,actualMicros:null,candidates:[{id:`candidate-${iteration}`,state:iteration===3?"proposed":"rejected",provenance:{usage:{input_tokens:10}}}],events:[{kind:"decision",payload:{reason:iteration===1?"Too abstract":"Too overloaded"}}]}));const output=report(p);assert.ok(output.includes("Attempts: 3"));assert.ok(output.includes("1500000"));assert.ok(output.includes("further work requires explicit operator escalation"));assert.ok(output.includes("third observation is not a recorded rejection"));assert.ok(output.includes("**proposed**"));});
test("QC modules contain no acquisition writer/provider dispatch or canonical writer path",async()=>{for(const file of ["lib/platform/operator-qc/context.ts","lib/platform/operator-qc/model.ts","scripts/operator-qc.ts","scripts/operator-qc/render.ts"]){const source=await readFile(file,"utf8");assert.ok(!/from ["'][^"']*(?:acquisition\/(?:service|openai|application)|canonical\/writes)/.test(source));assert.ok(!/\b(?:generateImage|ingestDisposable|writeCanonical|\.dispatch\()/.test(source));}});
