import { sql } from "drizzle-orm";
import { pgTable, uuid, text, integer, jsonb, timestamp, unique, index, check, foreignKey } from "drizzle-orm/pg-core";
import { webPresences } from "./web-presences";

export const externalWork = pgTable("external_work", {
  id: uuid("id").defaultRandom().primaryKey(),
  webPresenceId: uuid("web_presence_id").notNull().references(() => webPresences.id),
  capability: text("capability").notNull(),
  identity: text("identity").notNull(),
  contextDigest: text("context_digest").notNull(),
  context: jsonb("context").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  templateVersion: text("template_version").notNull(),
  iteration: integer("iteration").notNull(),
  status: text("status").notNull().default("queued"),
  version: integer("version").notNull().default(1),
  attempts: integer("attempts").notNull().default(0),
  retries: integer("retries").notNull().default(0),
  leaseToken: uuid("lease_token"),
  leaseUntil: timestamp("lease_until", { withTimezone: true }),
  budgetMicros: integer("budget_micros").notNull(),
  reservedMicros: integer("reserved_micros").notNull().default(0),
  actualMicros: integer("actual_micros"),
  result: jsonb("result").notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [
  unique("external_work_owner_id_unique").on(t.webPresenceId, t.id),
  unique("external_work_identity_unique").on(t.webPresenceId, t.identity),
  index("external_work_queue_idx").on(t.status, t.leaseUntil),
  index("external_work_need_idx").on(t.webPresenceId, t.contextDigest),
  check("external_work_capability", sql`${t.capability} IN ('image-generation','editorial-reconciliation')`),
  check("external_work_status", sql`${t.status} IN ('queued','running','awaiting-review','completed','failed','cancelled')`),
  check("external_work_digest", sql`${t.contextDigest} ~ '^[a-f0-9]{64}$' AND ${t.identity} ~ '^[a-f0-9]{64}$'`),
  check("external_work_bounds", sql`${t.version}>0 AND ${t.iteration} BETWEEN 1 AND 2 AND ${t.attempts} BETWEEN 0 AND 3 AND ${t.retries} BETWEEN 0 AND 2 AND ${t.budgetMicros}>0 AND ${t.reservedMicros} BETWEEN 0 AND ${t.budgetMicros} AND (${t.actualMicros} IS NULL OR ${t.actualMicros}>=0)`),
  check("external_work_payload", sql`octet_length(${t.context}::text)<=16384 AND octet_length(${t.result}::text)<=8192`),
]);

export const mediaCandidates = pgTable("media_candidates", {
  id: uuid("id").defaultRandom().primaryKey(),
  webPresenceId: uuid("web_presence_id").notNull(),
  workId: uuid("work_id").notNull(),
  revision: integer("revision").notNull().default(1),
  version: integer("version").notNull().default(1),
  state: text("state").notNull().default("proposed"),
  sourceKind: text("source_kind").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  quarantineKey: text("quarantine_key").notNull(),
  bytesDigest: text("bytes_digest").notNull(),
  subjectDigest: text("subject_digest").notNull(),
  provenanceDigest: text("provenance_digest").notNull(),
  provenance: jsonb("provenance").notNull(),
  width: integer("width").notNull(),
  height: integer("height").notNull(),
  mimeType: text("mime_type").notNull(),
  policyVersion: text("policy_version").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [
  foreignKey({columns:[t.webPresenceId,t.workId],foreignColumns:[externalWork.webPresenceId,externalWork.id],name:"media_candidates_owned_work_fk"}),
  unique("media_candidates_owner_id_unique").on(t.webPresenceId,t.id),
  unique("media_candidates_one_per_work_unique").on(t.workId),
  index("media_candidates_retention_idx").on(t.webPresenceId,t.state,t.expiresAt),
  check("media_candidates_state",sql`${t.state} IN ('proposed','rejected','approved','ingested','expired','revoked')`),
  check("media_candidates_format",sql`${t.sourceKind}='generated-illustrated' AND ${t.mimeType} IN ('image/png','image/jpeg','image/webp') AND ${t.width}>0 AND ${t.height}>0 AND ${t.width}::bigint*${t.height}<=40000000 AND ${t.revision}>0 AND ${t.version}>0`),
  check("media_candidates_digests",sql`${t.bytesDigest} ~ '^[a-f0-9]{64}$' AND ${t.subjectDigest} ~ '^[a-f0-9]{64}$' AND ${t.provenanceDigest} ~ '^[a-f0-9]{64}$' AND ${t.quarantineKey}='objects/'||${t.bytesDigest}`),
  check("media_candidates_provenance",sql`octet_length(${t.provenance}::text)<=16384`),
]);

export const externalWorkEvents = pgTable("external_work_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  webPresenceId: uuid("web_presence_id").notNull(),
  workId: uuid("work_id").notNull(),
  candidateId: uuid("candidate_id"),
  kind: text("kind").notNull(),
  payload: jsonb("payload").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, t => [
  foreignKey({columns:[t.webPresenceId,t.workId],foreignColumns:[externalWork.webPresenceId,externalWork.id],name:"external_work_events_owned_work_fk"}),
  foreignKey({columns:[t.webPresenceId,t.candidateId],foreignColumns:[mediaCandidates.webPresenceId,mediaCandidates.id],name:"external_work_events_owned_candidate_fk"}),
  index("external_work_events_work_idx").on(t.webPresenceId,t.workId,t.createdAt),
  index("external_work_events_candidate_idx").on(t.webPresenceId,t.candidateId,t.createdAt),
  check("external_work_events_kind",sql`${t.kind} IN ('queued','dispatch','result','failure','retry','stale','decision','ingestion','cancel','lease-expired','cleanup')`),
  check("external_work_events_payload",sql`octet_length(${t.payload}::text)<=8192`),
]);
