import { randomUUID } from "node:crypto";
import { choice,fingerprint,object,text,uuid } from "../canonical/model";

export const checks=["visual-needs","imagery","content","canonical-truth","proofreading","actions","conversion-path","rendering","accessibility","brand","completeness","readiness"] as const;
export type Check=typeof checks[number];
export const checkQuestions:Record<Check,string>={"visual-needs":"Are critical visual needs resolved or adequately reassessed?",imagery:"Is imagery useful, appropriate, permission-cleared and non-misleading?",content:"Is the message coherent, readable and free of obvious duplication?","canonical-truth":"Do rendered claims match confirmed knowledge and Offerings without contradictions?",proofreading:"Have obvious spelling/grammar issues been reviewed without silent rewriting?",actions:"Are labels, destinations and expectations consistent?","conversion-path":"Can the intended visitor understand the offer and take a valid next step?",rendering:"Do supported routes and representative responsive views work?",accessibility:"Are reading order, keyboard behavior, contrast and image alternatives sound?",brand:"Does the result fit the accepted Visual Direction without forced imagery?",completeness:"Are major Sections finished and claims supported?",readiness:"Can the customer meaningfully review this exact outcome now?"};
export const statuses=["pass","finding","not applicable","not assessed"] as const;
export const classifications=["literal-subject","simple-story","structured-relationship","proof-evidence","atmosphere-brand","no-visual"] as const;
export const choices=["customer-owned","existing-site","stock","generated","deterministic","commissioned","omit","refine-brief"] as const;
export type Row=Record<string,unknown>;
export type Reference={pageId?:string;sectionId?:string;field?:string;candidateId?:string};
export type Finding={id:string;reference:Reference;check:Check;severity:"blocker"|"required correction"|"non-critical observation";problem:string;evidence:string;effects:("accuracy"|"relevance"|"clarity"|"trust"|"conversion")[];visitorProblem:string;expectedImprovement:string;responsible:string;nextAction:string;status:"open"|"resolved"|"deferred";closure?:string;deferral?:string};
export type Brief={context:{sectionId:string;fingerprint:string};classification:typeof classifications[number];semanticGoal:string;subject?:string;scene?:string;setting?:string;visualStory:string;keyElements:string[];exclusions:string[];composition:string;orientation:"landscape"|"portrait"|"square";styleTone:string;brandConstraints:string[];truthBoundary:"illustrative"|"representative"|"actual-evidence";acceptanceCriteria:string[];workPolicy:{maxAttempts:number;maxRetries:number;budgetMicros:number;stopCondition:string}};
export type Need={sectionId:string;pageId:string;route:string;role:string;importance:string;purpose:string;source:string;permission:string;classification:typeof classifications[number]|"unassessed";copy:unknown;fallback:string;history:Row[];assets:Row[];heroDecision?:string[]};
export type Resolution={sectionId:string;choice:typeof choices[number];classification:typeof classifications[number];criticality:"critical"|"non-critical";disposition:"requires-resolution"|"adequate-fallback";reason:string;disclosure:string};
export type Technical={status:"not assessed"|"collected"|"failed";buildId:string|null;renderContext:string;routes:Row[];views:Row[];limitations:string[]};
export type Basis={version:1;reviewedAt:string;target:{organizationId:string;webPresenceId:string;managedSiteId:string};canonicalFingerprint:string;siteFingerprint:string;acquisitionFingerprint:string;contextFingerprint:string;presentation:unknown;routes:Row[];sections:Row[];actions:Row[];truth:Row[];needs:Need[];acquisition:Row[];technical:Technical;limitations:string[]};
export type Packet={version:1;basis:Basis;basisDigest:string;checklist:Record<Check,{status:typeof statuses[number];note:string}>;findings:Finding[];resolutions:Resolution[];briefs:Brief[];journal:{actor:string;reason:string;at:string;operation:string}[];attestations:{actor:string;reason:string;at:string;decision:"ready"|"not-ready";reviewDigest:string;contextFingerprint:string;localOnly:true}[]};
const boundedList=(v:unknown,max=12)=>{if(!Array.isArray(v)||v.length>max)throw Error("Bounded list required");return v.map(x=>text(x,500));};
export function createPacket(basis:Basis):Packet {
  return {version:1,basis,basisDigest:fingerprint(basis),checklist:Object.fromEntries(checks.map(c=>[c,{status:"not assessed",note:"Human operator review required"}])) as Packet["checklist"],findings:[],resolutions:[],briefs:[],journal:[],attestations:[]};
}
export function validateReference(packet:Packet,value:unknown):Reference {
  const r=object(value,["pageId","sectionId","field","candidateId"]),ref:Reference={};
  if(r.pageId!==undefined){ref.pageId=uuid(r.pageId);if(!packet.basis.routes.some(p=>p.id===ref.pageId))throw Error("Foreign Page");}
  if(r.sectionId!==undefined){ref.sectionId=uuid(r.sectionId);const s=packet.basis.sections.find(s=>s.id===ref.sectionId);if(!s||ref.pageId&&s.page_id!==ref.pageId)throw Error("Foreign Section");}
  if(r.candidateId!==undefined){ref.candidateId=uuid(r.candidateId);const h=packet.basis.needs.find(n=>n.history.some(w=>(w.candidates as Row[])?.some(c=>c.id===ref.candidateId)));if(!h||ref.sectionId&&h.sectionId!==ref.sectionId||ref.pageId&&h.pageId!==ref.pageId)throw Error("Foreign candidate");}
  if(r.field!==undefined){if(!ref.sectionId)throw Error("Field requires Section");ref.field=text(r.field,100);if(!/^[a-zA-Z][a-zA-Z0-9_.-]*$/.test(ref.field))throw Error("Invalid field reference");}
  return ref;
}
export function normalizeFinding(packet:Packet,value:unknown):Finding {
  const r=object(value,["id","reference","check","severity","problem","evidence","effects","visitorProblem","expectedImprovement","responsible","nextAction","status","closure","deferral"]);
  const f:Finding={id:r.id===undefined?randomUUID():uuid(r.id),reference:validateReference(packet,r.reference),check:choice(r.check,checks),severity:choice(r.severity,["blocker","required correction","non-critical observation"]),problem:text(r.problem,1000),evidence:text(r.evidence,1500),effects:boundedList(r.effects,5).map(e=>choice(e,["accuracy","relevance","clarity","trust","conversion"])),visitorProblem:text(r.visitorProblem,1000),expectedImprovement:text(r.expectedImprovement,1000),responsible:text(r.responsible,120),nextAction:text(r.nextAction,1000),status:choice(r.status,["open","resolved","deferred"]),...(r.closure===undefined?{}:{closure:text(r.closure,1500)}),...(r.deferral===undefined?{}:{deferral:text(r.deferral,1000)})};
  if(!f.effects.length||f.status==="resolved"&&(!f.closure||f.deferral)||f.status==="deferred"&&(f.severity!=="non-critical observation"||!f.deferral||f.closure)||f.status==="open"&&(f.closure||f.deferral))throw Error("Invalid finding closure/deferral");return f;
}
export function normalizeBrief(packet:Packet,value:unknown):Brief {
  const r=object(value,["context","classification","semanticGoal","subject","scene","setting","visualStory","keyElements","exclusions","composition","orientation","styleTone","brandConstraints","truthBoundary","acceptanceCriteria","workPolicy"]),ctx=object(r.context,["sectionId","fingerprint"]),policy=object(r.workPolicy,["maxAttempts","maxRetries","budgetMicros","stopCondition"]);
  const sectionId=uuid(ctx.sectionId);if(!packet.basis.needs.some(n=>n.sectionId===sectionId)||ctx.fingerprint!==packet.basis.contextFingerprint)throw Error("Stale/foreign brief context");
  for(const k of ["maxAttempts","maxRetries","budgetMicros"]){if(!Number.isSafeInteger(policy[k])||Number(policy[k])<0||Number(policy[k])>(k==="budgetMicros"?2000000000:20))throw Error("Invalid work policy");}
  const brief:Brief={context:{sectionId,fingerprint:String(ctx.fingerprint)},classification:choice(r.classification,classifications),semanticGoal:text(r.semanticGoal,500),visualStory:text(r.visualStory,1000),keyElements:boundedList(r.keyElements,5),exclusions:boundedList(r.exclusions,20),composition:text(r.composition,500),orientation:choice(r.orientation,["landscape","portrait","square"]),styleTone:text(r.styleTone,500),brandConstraints:boundedList(r.brandConstraints),truthBoundary:choice(r.truthBoundary,["illustrative","representative","actual-evidence"]),acceptanceCriteria:boundedList(r.acceptanceCriteria),workPolicy:{maxAttempts:Number(policy.maxAttempts),maxRetries:Number(policy.maxRetries),budgetMicros:Number(policy.budgetMicros),stopCondition:text(policy.stopCondition,500)}};
  for(const key of ["subject","scene","setting"] as const)if(r[key]!==undefined)brief[key]=text(r[key],500);
  if(!brief.acceptanceCriteria.length||brief.classification==="proof-evidence"&&brief.truthBoundary!=="actual-evidence")throw Error("Evidence/acceptance boundary");return brief;
}
export function reviewDigest(p:Packet){return fingerprint({basisDigest:p.basisDigest,checklist:Object.fromEntries(Object.entries(p.checklist).filter(([k])=>k!=="readiness")),findings:p.findings,resolutions:p.resolutions,briefs:p.briefs,journal:p.journal});}
export function assertFresh(p:Packet,basis:Basis){
  if(p.version!==1||p.basisDigest!==fingerprint(p.basis)||p.basis.contextFingerprint!==basis.contextFingerprint)throw Error("Stale or altered QC context; prepare a new packet");
  object(p.checklist,checks);for(const c of checks){const s=p.checklist[c];choice(s.status,statuses);text(s.note,1000);if(s.status==="not applicable"&&!["imagery","visual-needs"].includes(c))throw Error("Invalid mandatory checklist status");}
  if(p.findings.length>100||p.journal.length>500||p.attestations.length>100)throw Error("Local review bounds");
  for(const f of p.findings)normalizeFinding(p,f);
  for(const r of p.resolutions)saveResolution({...p,journal:[]},r,"validation");
  for(const b of p.briefs)normalizeBrief(p,b);
  for(const a of p.attestations){text(a.actor,120);text(a.reason,1000);choice(a.decision,["ready","not-ready"]);if(!Number.isFinite(Date.parse(a.at))||a.localOnly!==true)throw Error("Invalid local attestation");}
}
function edited(p:Packet,actor:string,reason:string,operation:string){const next=structuredClone(p);if(next.journal.length>=500)throw Error("Review journal limit reached");next.journal.push({actor:text(actor,120),reason:text(reason,1000),at:new Date().toISOString(),operation});next.checklist.readiness={status:"not assessed",note:"Local review changed; attestation must be renewed"};return next;}
export function setCheck(p:Packet,check:Check,status:typeof statuses[number],note:string,actor:string){choice(check,checks);choice(status,statuses);if(check==="readiness")throw Error("Use explicit readiness attestation");if(status==="not applicable"&&(!["imagery","visual-needs"].includes(check)||check==="visual-needs"&&p.basis.needs.length>0||check==="imagery"&&p.basis.needs.some(n=>n.assets.length>0)))throw Error("Applicable/mandatory check cannot be skipped");const n=edited(p,actor,note,`check:${check}`);n.checklist[check]={status,note:text(note,1000)};return n;}
export function saveFinding(p:Packet,input:unknown,actor:string){const f=normalizeFinding(p,input);if(p.findings.length>=100&&!p.findings.some(x=>x.id===f.id))throw Error("Finding limit");const n=edited(p,actor,f.nextAction,"finding");n.findings=[...n.findings.filter(x=>x.id!==f.id),f];return n;}
export function saveResolution(p:Packet,input:unknown,actor:string){const r=object(input,["sectionId","choice","classification","criticality","disposition","reason","disclosure"]),sectionId=uuid(r.sectionId);if(!p.basis.needs.some(n=>n.sectionId===sectionId))throw Error("Foreign visual need");const result:Resolution={sectionId,choice:choice(r.choice,choices),classification:choice(r.classification,classifications),criticality:choice(r.criticality,["critical","non-critical"]),disposition:choice(r.disposition,["requires-resolution","adequate-fallback"]),reason:text(r.reason,1000),disclosure:text(r.disclosure,1000)};const n=edited(p,actor,result.reason,"proposed-visual-resolution");n.resolutions=[...n.resolutions.filter(x=>x.sectionId!==sectionId),result];return n;}
export function saveBrief(p:Packet,input:unknown,actor:string){const b=normalizeBrief(p,input),n=edited(p,actor,b.semanticGoal,"proposed-brief");n.briefs=[...n.briefs.filter(x=>x.context.sectionId!==b.context.sectionId),b];return n;}
export function assessment(p:Packet){
  const reasons:string[]=[];for(const c of checks.filter(c=>c!=="readiness")){const s=p.checklist[c].status;if(s!=="pass"&&s!=="not applicable")reasons.push(`${c}: ${s}`);}
  for(const f of p.findings)if(f.status==="open"&&f.severity!=="non-critical observation")reasons.push(`${f.severity}: ${f.problem}`);
  for(const need of p.basis.needs){const r=p.resolutions.find(r=>r.sectionId===need.sectionId);if(!r)reasons.push(`Visual need unassessed: ${need.role}`);else if(r.criticality==="critical"&&r.disposition!=="adequate-fallback")reasons.push(`Critical visual unresolved: ${need.role}`);if(r?.choice==="refine-brief"&&!p.briefs.some(b=>b.context.sectionId===r.sectionId))reasons.push(`Structured brief missing: ${need.role}`);}
  const views=p.basis.technical.views;
  const coverage=p.basis.routes.every(r=>["desktop","tablet","mobile"].every(view=>views.filter(v=>v.pageId===r.id&&v.view===view).length===1));
  if(p.basis.technical.status!=="collected"||p.basis.technical.routes.length!==p.basis.routes.length||p.basis.technical.routes.some(r=>r.status!==200)||views.length!==p.basis.routes.length*3||!coverage||views.some(v=>v.overflow||v.brokenImages||v.missingAlt||v.h1Count!==1))reasons.push("Technical evidence incomplete or failing");
  const digest=reviewDigest(p),a=p.attestations.at(-1),attested=!!a&&a.decision==="ready"&&a.reviewDigest===digest&&a.contextFingerprint===p.basis.contextFingerprint;
  return {eligibleForAttestation:reasons.length===0,customerReady:reasons.length===0&&attested,operatorAttestationRequired:!attested,reasons,localOnly:true,customerAcceptance:false,publicationAuthorized:false};
}
export function attest(p:Packet,decision:"ready"|"not-ready",actor:string,reason:string){choice(decision,["ready","not-ready"]);if(decision==="ready"&&!assessment(p).eligibleForAttestation)throw Error("Readiness refused: unresolved findings/checks/technical evidence");const n=structuredClone(p);n.attestations.push({actor:text(actor,120),reason:text(reason,1000),at:new Date().toISOString(),decision,reviewDigest:reviewDigest(p),contextFingerprint:p.basis.contextFingerprint,localOnly:true});n.checklist.readiness={status:decision==="ready"?"pass":"finding",note:text(reason,1000)};return n;}
